#!/usr/bin/bash
termux-setup-storage
pkg update
pkg upgrade -y
pkg install root-repo -y
pkg install x11-repo -y
pkg install termux-api -y
pkg install git -y
pkg install wget -y
pkg install curl -y
pkg install python -y
pip install python2 -y
MATHLIB="m" pip install pandas -y
pkg install nano -y
pkg install php -y
pkg install ruby -y
pkg install mc -y
pkg install bash -y
pkg install toilet -y
pkg install figlet -y
pkg install cowsay -y
pkg install cloudflared -y
pkg install openssh -y
pkg install sshpass -y
gem install lolcat -y
pip install requests -y
pip install mechanize -y 
python3 -m pip install --upgrade pip
pkg install tigervnc -y
pkg install libuuid -y
pip install openpyxl -y
pkg install numpy -y
pkg install scipy -y
pkg install python-tkinter -y
pip install tkintertable -y
pip install customtkinter -y
pip install XlsxWriter -y
pip install colorama -y
























