#!/usr/bin/bash
termux-setup-storage -y
pkg update
pkg upgrade
pkg install x11-repo -y
pkg install termux-api -y
pkg install wget -y
pkg install curl -y
pkg install python -y
pkg install python2 -y
pkg install nano -y
pkg install php -y
#pkg install apache2 -y
pkg install php-apache -y
pkg install mariadb -y
pkg install phpmyadmin -y
pkg install ruby -y
pkg install mc -y
pkg install bash -y
pkg install toilet -y
pkg install figlet -y
pkg install cowsay -y
#pkg install cloudflared -y
pkg install openssh -y
pkg install sshpass -y
gem install lolcat
#pip install requests
#pip install mechanize
#pkg install tigervnc -y
#pip install openpyxl
#pkg install python-tkinter -y
#pkg install xfce4 -y
#pkg install xfce4-terminal -y
#pip install tkintertable
#pip install customtkinter
#pip install pysimplegui
#pip install XlsxWriter
#pip install colorama
#pip install PythonTurtle
#MATHLIB="m" pip install pandas
